In [3]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [4]:
#bimu, implemented applications (cost estimation, quantity take-off, 
#facility management, procurement management, visualisation, lifecycle maintenance),
#IM11 (willing to use BIM for project communication)

In [5]:
xy = np.genfromtxt ('C:/Users/z5023853/Google Drive/Separated dataset_ML/xy.csv', 
                    delimiter = ',',usecols = (0,1,2,3,4,5,6,7,8,9), skip_header=1)

In [6]:
xy

array([[ 0.,  0.,  0., ...,  0.,  3.,  4.],
       [ 1.,  0.,  0., ...,  0.,  4.,  5.],
       [ 1.,  0.,  1., ...,  0.,  4.,  5.],
       ..., 
       [ 1.,  0.,  0., ...,  1.,  2.,  5.],
       [ 1.,  1.,  0., ...,  0.,  2.,  5.],
       [ 1.,  1.,  1., ...,  1.,  4.,  7.]])

In [9]:
enc_xy

array([[ 1.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1.,  1., ...,  1.,  0.,  0.],
       [ 0.,  1.,  1., ...,  1.,  0.,  0.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  0.,  0.],
       [ 0.,  1.,  0., ...,  1.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  1.]])

In [8]:
enc = OneHotEncoder ()
enc.fit (xy)
print ('feature indices',enc.feature_indices_)
#Number of values per feature
print ('number of values per feature', enc.n_values_)
enc_xy = enc.transform(xy).toarray()

feature indices [ 0  2  4  6  8 10 12 14 16 22 30]
number of values per feature [2 2 2 2 2 2 2 2 6 8]


In [20]:
n = 2
for n in range (2,300):
    xk = KMeans (n_clusters=n, algorithm='full')
    xk.fit_predict (xy)
    #print (xk.score (xy))
    #print (xk.cluster_centers_)
    print (xk.inertia_)

1382.25869276
974.134085213
852.06260467
744.474645391
699.481056278
659.075146743
643.118949981
616.16795432
589.825820659
577.913632709
559.624709005
542.419073228
527.789766047
511.952766486
495.341895082
482.825004907
477.47969313
471.425329743
454.922949432
445.070933233
438.578083466
425.42678098
413.57915804
410.470289064
404.097724334
397.661252419
386.62820521
381.450693751
378.105252694
369.873978799
365.009458026
354.2105602
353.45391455
347.713361638
340.098079771
331.634368409
330.460366448
321.402684407
319.592547077
313.662631813
309.25952381
305.342765894
298.892665668
293.973051948
290.451884227
289.740548341
277.243073593
278.611904762
275.158225108
270.972136197
261.601190476
259.810894661
259.988275613
255.425632701
251.708369408
246.310858586
242.619155844
239.65523088
241.148304473
238.336183261
231.599675325
228.732936508
226.11984127
225.409226884
221.662337662
218.217063492
217.074664225
213.021428571
208.779761905
206.292388167
205.069480519
201.323773449
201.

In [22]:
xk_tuned = KMeans (n_clusters=4, algorithm='full')
xk_tuned.fit_predict (xy)

array([2, 2, 2, 1, 3, 2, 2, 0, 0, 0, 3, 3, 1, 1, 1, 2, 3, 0, 1, 2, 2, 2, 1,
       0, 2, 2, 2, 0, 1, 1, 3, 0, 2, 1, 1, 0, 1, 3, 1, 0, 2, 0, 0, 1, 1, 3,
       0, 0, 2, 3, 2, 2, 1, 1, 2, 1, 1, 3, 1, 2, 2, 1, 0, 2, 1, 1, 0, 0, 3,
       0, 1, 1, 1, 3, 3, 3, 1, 1, 1, 1, 2, 3, 2, 3, 1, 2, 1, 1, 2, 2, 1, 1,
       2, 1, 1, 1, 1, 1, 2, 3, 2, 1, 0, 2, 3, 1, 1, 2, 1, 1, 2, 1, 1, 3, 3,
       1, 1, 2, 3, 1, 3, 1, 3, 3, 3, 3, 1, 3, 1, 3, 1, 1, 3, 3, 1, 2, 1, 1,
       1, 2, 2, 2, 3, 2, 1, 1, 1, 1, 2, 3, 3, 1, 2, 1, 1, 1, 2, 0, 0, 1, 1,
       2, 2, 1, 2, 2, 2, 2, 1, 3, 2, 0, 0, 1, 1, 3, 3, 1, 3, 2, 1, 3, 2, 2,
       3, 3, 1, 2, 0, 1, 3, 0, 1, 2, 3, 2, 2, 0, 1, 3, 3, 2, 3, 2, 3, 1, 1,
       1, 2, 2, 1, 1, 3, 1, 2, 2, 1, 3, 3, 3, 2, 3, 0, 3, 2, 3, 2, 3, 1, 3,
       3, 2, 2, 1, 1, 0, 2, 2, 1, 3, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1,
       1, 1, 1, 1, 3, 1, 1, 2, 2, 1, 1, 1, 3, 3, 3, 2, 1, 3, 1, 0, 2, 1, 2,
       2, 0,

In [23]:
label = xk_tuned.fit_predict (xy)

In [24]:
np.savetxt("label_re.csv", label, delimiter=',')